name: dataclass
description: DataClass annotation for dataclass_generator. Used for generating base class with equals, hashCode, toString, copyWith methods.
version: 0.3.0+1
author: Jaroslaw Butajlo <jaroslaw.butajlo@gmail.com>
homepage: https://github.com/jarekb123/dart_dataclass

environment:
  sdk: ">2.9.0 <3.0.0"

dependencies:
  collection: 1.15.0-nullsafety.2

dev_dependencies:
