name: dataclass_beta_generator
description: DataClass annotation for dataclass_generator. Used for generating base class with equals, hashCode, toString, copyWith methods.
version: 1.0.0
author: Jaroslaw Butajlo <jaroslaw.butajlo@gmail.com>, Nikita Kozlov <nick@nk2.eu>
homepage: https://github.com/nk2ishere/dart_dataclass

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dataclass_beta:
    git:
      url: https://github.com/nk2IsHere/dart_dataclass.git
      path: dataclass
      ref: ae55d20
  source_gen: ^1.0.0
  code_builder: ^4.0.0


dev_dependencies:
  build_test:
  build_runner:
  test:
